# Generated by Django 5.0.1 on 2024-01-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_products_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="quantity",
        ),
    ]
