# Generated by Django 5.0.1 on 2024-02-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_products_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="in_stock",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
