# Generated by Django 5.0.1 on 2024-02-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imagea',
            field=models.ImageField(default=3, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='imageb',
            field=models.ImageField(default=2, upload_to='media'),
            preserve_default=False,
        ),
    ]
