# Generated by Django 5.0.1 on 2024-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_products_quantity_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="in_stock",
            field=models.IntegerField(null=True),
        ),
    ]
