# Generated by Django 5.0.1 on 2024-01-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_listed",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(default=3, upload_to="photos/products"),
            preserve_default=False,
        ),
    ]
