# Generated by Django 5.0.1 on 2024-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_rename_categoryname_category_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
