# Generated by Django 5.0.1 on 2024-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ptoduct_name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
