# Generated by Django 5.0.1 on 2024-02-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_ptoduct_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ptoduct_name',
        ),
    ]
