# Generated by Django 5.0.1 on 2024-02-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_ptoduct_name'),
        ('home', '0009_useraddress_delete_userprofile'),
        ('products', '0008_products_quantity_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(max_length=50)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('is_cancel', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.useraddress')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermodelss')),
                ('variant_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variant')),
            ],
        ),
    ]
