# Generated by Django 5.0.1 on 2024-02-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_orderdetails_coupen_apply_orderdetails_coupen_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetails",
            name="coupen_apply",
        ),
        migrations.RemoveField(
            model_name="orderdetails",
            name="coupen_code",
        ),
        migrations.RemoveField(
            model_name="orderdetails",
            name="discount_amount",
        ),
    ]
