# Generated by Django 5.0.1 on 2024-02-24 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_orderdetails_coupen_apply_orderdetails_coupen_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="coupen_apply",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="coupen_code",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="cart.coupon"
            ),
        ),
    ]
