# Generated by Django 5.0.1 on 2024-01-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usermodelss',
        ),
    ]
