# Generated by Django 5.0.1 on 2024-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_usermodelss_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelss',
            name='is_block',
            field=models.BooleanField(default=True),
        ),
    ]
