# Generated by Django 5.0.1 on 2024-02-10 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_usermodelss_is_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=225)),
                ('state_country', models.CharField(max_length=20)),
                ('post_pin', models.CharField(max_length=20)),
                ('aemail', models.CharField(max_length=20)),
                ('aphone', models.BigIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermodelss')),
            ],
        ),
    ]
