# Generated by Django 5.0.1 on 2024-02-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_useraddress_delete_userprofile'),
        ('products', '0008_products_quantity_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermodelss')),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variant')),
            ],
        ),
    ]
