# Generated by Django 5.0.1 on 2024-02-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='variant_id',
        ),
    ]
