# Generated by Django 5.0.1 on 2024-02-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_wishlist_variant_id'),
        ('products', '0008_products_quantity_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='vaiant_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='products.variant'),
            preserve_default=False,
        ),
    ]
