# Generated by Django 5.0.1 on 2024-02-17 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_wishlist_vaiant_id'),
        ('products', '0008_products_quantity_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='vaiant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variant'),
        ),
    ]
