# Generated by Django 5.0.1 on 2024-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_walletuser_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletuser',
            name='amountt',
            field=models.IntegerField(default=0),
        ),
    ]
